version: '3'

services:
  redis-server:
    image: redis

  nginx:
    build: ./nginx
    container_name: ms_nginx
    depends_on:
      - store
      - users
    ports:
      - '80:80'

  store:
    build: ./store
    container_name: ms_store
    depends_on:
      - redis-server
    # volumes:
    #     - "./store:/src/app"
    # working_dir: "/src/app"
    ports:
      # - "8080:8080"
      # - "5858:5858"
      - '5000:8081'
    # command: npm run start
    command: npm run start

  users:
    build: ./users
    container_name: ms_users
    depends_on:
      - redis-server
    # volumes:
    #     - "./users:/src/app"
    # working_dir: "/src/app"
    ports:
      - '5001:8081'
    command: npm run start
